[package]
name = "news_flash_gtk"
version = "0.1.0"
authors = ["Jan Lukas Gernert <jangernert@gmail.com>"]
edition = "2018"

[dependencies]
log = "0.4"
chrono = "0.4"
rust-embed = "4.2"
cairo-rs = "0.5"
failure = "0.1"
serde = "1.0"
serde_json = "1.0"
news-flash = { git = "http://gitlab.com/news-flash/news_flash_base.git" }

[dependencies.gtk]
features = ["v3_22"]
version = "0.5"

[dependencies.gio]
features = ["v2_50"]
version = "0.5"

[dependencies.gdk]
version = "0.9"
