[package]
name = "news_flash_gtk"
version = "0.1.0"
authors = ["Jan Lukas Gernert <jangernert@gmail.com>"]
edition = "2018"

[dependencies]
log = "0.4"
chrono = "0.4"
rust-embed = { version = "5.1", features = ["debug-embed"] }
cairo-rs = "0.7"
failure = "0.1"
serde = "1.0"
serde_json = "1.0"
gtk = { version = "0.7", features = ["v3_24"] }
gio = { version = "0.7", features = ["v2_58"] }
gdk = { version = "0.11", features = ["v3_24"] }
libhandy = { version = "0.4", features=["v0_0_10"] }
gdk-pixbuf = "0.7"
pango = "0.7"
webkit2gtk = { version = "0.8", features = ["v2_16"] }
glib = "0.8"
log4rs = "0.8"
dirs = "2.0"
color-backtrace = "0.2"
lazy_static = "1.4"
reqwest = "0.9"
news-flash = { git = "http://gitlab.com/news-flash/news_flash_base.git" }
