[package]
name = "news_flash_gtk"
version = "0.1.0"
authors = ["Jan Lukas Gernert <jangernert@gmail.com>"]
edition = "2018"

[dependencies]
log = "0.4"
chrono = "0.4"
rust-embed = { version = "4.3", features = ["debug-embed"] }
cairo-rs = "0.6"
failure = "0.1"
serde = "1.0"
serde_json = "1.0"
serde_derive = "1.0"
gtk = { version = "0.6", features = ["v3_22_30"] }
gio = { version = "0.6", features = ["v2_56"] }
gdk = { version = "0.10", features = ["v3_22"] }
gdk-pixbuf = "0.6"
pango = "0.6"
webkit2gtk = { version = "0.6", features = ["v2_16"] }
glib = "0.7"
log4rs = "0.8"
dirs = "1.0"
news-flash = { git = "http://gitlab.com/news-flash/news_flash_base.git" }
