[package]
name = "news_flash_gtk"
version = "0.1.0"
authors = ["Jan Lukas Gernert <jangernert@gmail.com>"]

[dependencies]
gobject-subclass = "0.2"
glib-sys = "0.7"
gobject-sys = "0.7"
glib = "0.6"
gio = "0.5"
gdk = "0.9"
gdk-pixbuf = "0.5"
gtk = "0.5"
pango = "0.5"