[package]
name = "news_flash_gtk"
version = "0.1.0"
authors = ["Jan Lukas Gernert <jangernert@gmail.com>"]

[dependencies]
rust-embed = "3.0"

[dependencies.gtk]
features = ["v3_22"]
version = "0.5"

[dependencies.gio]
features = ["v2_50"]
version = "0.5"

[dependencies.gdk]
version = "0.9"
